#!/usr/bin/env bash

# Update the package list
apt-get update

# Install nginx
apt-get install -y nginx

# Configure nginx to listen on port 80
sed -i 's/listen\s*80/listen 0.0.0.0:80/g' /etc/nginx/sites-available/default

# Configure nginx to serve "Hello World!" at the root location
echo "Hello World!" | tee /var/www/html/index.html

# Restart nginx
service nginx restart
