#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument.
#Accepts a string as an arguments
#Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#Ping the IP 5 times

if [[ "$1" -eq 0 ]]; then
	echo Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
	exit
fi
ping -c 5 "$1"
