#!/usr/bin/env bash
#Write a Bash script that:

#Creates the file /var/run/myscript.pid containing its PID
echo '$$' > /var/run/myscript.pid

while true; do
	#Displays To infinity and beyond indefinitely
	echo "To infinity and beyond"

	#Displays I hate the kill command when receiving a SIGTERM signal
	trap 'echo "I hate the kill"' SIGTERM

	#Displays Y U no love me?! when receiving a SIGINT signal
	trap 'echo "Y U no love me?!"' SIGINT

	#Deletes the file /var/run/myscript.pid & terminates itself when receiving a SIGQUIT or SIGTERM signal
	trap 'rm var/run/myscript.pid; exit' SIGQUIT
done
