#!/usr/bin/env bash
i=1
while [ $i -le 10 ]
do
	if [[ $i != 9 ]]
	then
		echo "Best School"
	else
		echo -e "Best School\nHi"
		#We could have still used: echo "Best School$'\n'Hi"
	fi
	i=$(( $i + 1))
done
