#!/usr/bin/env bash
#Print Best school unless
#i == 4 print bad luck
#i == 8 print good luck
i=1
while [ $i -le 10 ]; do
	if [[ $i == 4 ]]
	then
		echo "bad luck"
	elif [[ $i == 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$(($i + 1))
done
