#!/usr/bin/env bash
#Print Best school unless
#i == 4 print 4 print bad luck from China
#i == 9 print 9 bad luck from Japan
#i == 17 print 17 bad luck from Italy
i=1
while [ $i -le 20 ]
do
	if [[ $i == 4 ]]
	then
		echo -e "4\nbad luck from China"

	elif [[ $i == 9 ]]
	then
		echo -e "9\nbad luck from Japan"

	elif [[ $i == 17 ]]
	then
		echo -e "17\nbad luck from Italy"
	else
		echo "$i"
	fi
	i=$(($i + 1))
done
