#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
hour=0
min=0

while [ $hour -le 12 ]; do
	echo Hour: $hour
	while [ $min -le 58 ]; do
		min=$(($min + 1))
		echo $min
	done
	hour=$((hour + 1))
	min=0
done
