#!/usr/bin/env bash
# a Bash script that configures the container
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
