#!/usr/bin/env bash
# ssh_config

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    HostName 52.91.160.46
    User ubuntu
